CREATE TABLE topics (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  status VARCHAR(255) NOT NULL DEFAULT 'NOT_ANSWERED',
  author VARCHAR(255) NOT NULL,
  curso VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
